version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker
        - run:
          name: Create Initialisatiion script
          command: |
            sudo mkdir -p app/static app/templates
            sudo apt-get update
            sudo apt install git-all
            git clone https://github.com/ANSHUKPANDEY/Practice-Session.git 
            sudo cp -r pyapp/init.py app/
            sudo cp -r pyapp/views.py app/
            sudo pip install Flask
            sudo docker login -u anshukpandey --password Wyndham02$
      - run:  
          name: Build Docker Image
          command: |
           docker build -t anshukpandey/pythonapp:pytest -f pyapp/Dockerfile .
      - run:     
          name: Push Image To DockerHub
          command: |
           docker login -u anshukpandey --password Wyndham02$
           docker push anshukpandey/pythonapp:pytest


