version: 2.1
jobs:
  build:
    docker:
      - image: tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
    steps:
      - checkout
      - run:
          name: Create Initialisatiion script
          command: |
            mkdir -p app/static app/templates
            git clone https://github.com/ANSHUKPANDEY/Practice-Session.git 
            cp -r pyapp/init.py app/
            cp -r pyapp/views.py app/
      - run:  
          name: Build Docker Image
          command: |
           docker build -t pytest .
      - run:     
          name: Create docker container
          command: |
           docker run -d -p 56733:80 --name=pyapp pytest


